### ISSUE TITLE
Replace MLX code with PyTorch code on the Story of a tensor (for PyTorch) example

### ISSUE THREAD

**Issue by ncarandini** [neobundy/Deep-Dive-Into-AI-With-MLX-PyTorch#3]
The PyTorch version of the [Story of a tensor](https://github.com/neobundy/Deep-Dive-Into-AI-With-MLX-PyTorch/blob/master/book/001-story-of-a-tensor/story-of-a-tensor-torch.py) contains MLX code instead of PyTorch code.

**Comment by neobundy** [comment]
Mysterious things happen. PyTorch code restored. 👍
