### ISSUE TITLE
Eagle README shows wrong architecture

### ISSUE THREAD

**Issue by SmerkyG** [neobundy/Deep-Dive-Into-AI-With-MLX-PyTorch#6]
Hey, just wanted to let you know that the README about Eagle shows the RWKV-4 architecture, not RWKV-5 which is what Eagle uses. Sorry the paper isn't out yet for v5 so it may be hard to update, but you might want to just put a disclaimer in there for now that the description is of the earlier less powerful architecture...

**Comment by neobundy** [comment]
I added a disclaimer, but just to highlight, the source code repo I used is v5:

❗️Important Note - While the architecture discussed in the paper pertains to RWKV v4, the implementation details provided in this comprehensive analysis are derived from RWKV v5, the most current version.

**Comment by SmerkyG** [comment]
Thanks! I see the WKV operator formula is from RWKV-4 though and is now very different, so you might want to update that. There's no longer a denominator, and the decays are per channel, among other things. Haven't had time to read through fully yet but that jumped out at me.

**Comment by neobundy** [comment]
I believe there's a bit of a misunderstanding here. My focus is on discussing *the paper*, not on covering your most recent work.

I'm not attempting to take over anyone's project; my aim is solely to shed light on the paper. The age of a paper doesn't detract from its value; it can still hold significance.

If you're keen on presenting your newest developments, I'd encourage you to do so in a different paper.

I've made it clear which paper I'm delving into. It's important to remember that.

For instance, if I'm breaking down "Attention is all you need" and then the creators of the newest Transformer model approach me with claims of inaccuracy, urging me to cover their model instead, that wouldn't be just.

If for any reason you, as the rightful owner of any material discussed here, prefer this content not to be included in the repository, I fully respect your decision and am ready to remove it upon request.

**Comment by SmerkyG** [comment]
Sorry for any misunderstanding, we love the fact that you're discussing the v4 paper here! And it's certainly good background for v5.

I just saw the big headline and picture saying Eagle, then looked down and saw info about v4. :) Thanks for adding the disclaimer!

**Comment by neobundy** [comment]
I've revised the disclaimer. If you still believe the content shouldn't be presented as it currently is, please inform me.

## ❗️Crucial Disclaimer

The paper under discussion relates to RWKV version 4, whereas Eagle 7B represents the latest, version 5. The implementation specifics we are examining come from the version 5 source code repository. Researchers have indicated that version 5 introduces substantial enhancements over version 4, but the paper detailing version 5 has not yet been published. For more information, please refer to the official RWKV Blog and repository.

**Comment by neobundy** [comment]
I completely grasp your sentiments regarding the latest Eagle. Kindly share your updated formula, and I will add a note as you wish. If you could also provide a paragraph or two explaining why this update is essential for enhancing performance, that would be incredibly beneficial and a great learning opportunity for all of us reading the material as well 🤗

**Comment by neobundy** [comment]
Included an additional note in the section. 😊 If there's anything more to add or modify, just let me know. I also conducted a brief inference demo on the M2 Ultra (CPU fp32) and the RTX 4090 24GB (CUDA fp16) if you haven't checked it out yet: https://x.com/WankyuChoi/status/1753372744056725622?s=20

_**Note from the Researcher:** It has been brought to our attention by one of the researchers that the WKV operator formula discussed in this section is based on RWKV version 4. In RWKV version 5, there have been substantial updates to this formula, including the removal of the denominator and the introduction of channel-specific decay rates. These modifications are crucial for understanding the evolution from version 4 to 5. Once the paper on V5 is released, all the details will become much more transparent._ 

_The researcher emphasizes that the most notable enhancement in Eagle's updated WKV formulation is the transition from a vector-valued state to a substantially larger matrix-valued state. This shift enables the model to retain a more extensive amount of context in its memory, encompassing not only the contextual information but also its previous transformations of that context._
